<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ page
	import="com.generation.RiservaBellaJANA71.RiservaBella.entities.Animale"%>
<%
Animale a = (Animale) request.getAttribute("animale");
%>
<!-- a.getImg() 
		 	<a href="/dettaglimodificaanimale?id= a.getId() ">MODIFICA</a>  -->

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Gestione Amm. Animali</title>
<link
	href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
	rel="stylesheet"
	integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
	crossorigin="anonymous" />
<script
	src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
	integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
	crossorigin="anonymous"></script>

<script type="text/javascript">
	/*
	INIZIO PARTE PAGINE SCHEDA STANDARD E AMMINISTRATORE ANIMALI E PIANTE
	 */

	function nohide1() {
		document.getElementById("XX").hidden = false;
	}
	function hide1() {
		document.getElementById("XX").hidden = true;
	}
	function nohide2() {
		document.getElementById("XY").hidden = false;
	}
	function hide2() {
		document.getElementById("XY").hidden = true;
	}
	function nohide3() {
		document.getElementById("YY").hidden = false;
	}
	function hide3() {
		document.getElementById("YY").hidden = true;
	}
</script>

<style type="text/css">
body {
	background: rgb(144, 237, 139);
	background: radial-gradient(circle, rgba(144, 237, 139, 1) 41%,
		rgba(33, 107, 57, 1) 93%);
	font-family: "Gill Sans", "Gill Sans MT", Calibri, "Trebuchet MS",
		sans-serif;
}

button {
  background-color: white; 
  color: black; 
  border: 2px solid #216b39;
  border-radius: 5px;
  width: 100%;
  height: 50px;
  font-size: 30px;
  }
  
button:hover {
    background-color: #216b39; /* Green */
    color: white;
 }

#buttonRegistrati{
  background-color: #216b39;
}

#buttonModifica{
  height: 30px;
}
#buttonElimina{
  height: 30px;
}


#buttonModifica{
  font-size: 15px;
}

#buttonElimina{
  font-size: 15px;
}

#buttonIndietro{
  font-size: 15px;
}

#buttonAvanti{
  font-size: 15px;
}

.scale-down-top {
	-webkit-animation: scale-down-top 0.5s
		cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
	animation: scale-down-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* ----------------------------------------------
   * Generated by Animista on 2023-2-7 16:9:36
   * Licensed under FreeBSD License.
   * See http://animista.net/license for more info. 
   * w: http://animista.net, t: @cssanimista
   * ---------------------------------------------- */

/**
   * ----------------------------------------
   * animation scale-down-top
   * ----------------------------------------
   */
@
-webkit-keyframes scale-down-top { 0% {
	-webkit-transform: scale(1);
	transform: scale(1);
	-webkit-transform-origin: 50% 0%;
	transform-origin: 50% 0%;
}

100


%
{
-webkit-transform


:


scale
(


0
.5


)
;


transform


:


scale
(


0
.5


)
;


-webkit-transform-origin


:


50
%


0
%;


transform-origin


:


50
%


0
%;


}
}
@
keyframes scale-down-top { 0% {
	-webkit-transform: scale(1);
	transform: scale(1);
	-webkit-transform-origin: 50% 0%;
	transform-origin: 50% 0%;
}

100


%
{
-webkit-transform


:


scale
(


0
.5


)
;


transform


:


scale
(


0
.5


)
;


-webkit-transform-origin


:


50
%


0
%;


transform-origin


:


50
%


0
%;


}
}

/* slide fwd table*/
.slide-fwd-top {
	-webkit-animation: slide-fwd-top 0.5s
		cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
	animation: slide-fwd-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* ----------------------------------------------
   * Generated by Animista on 2023-2-7 17:34:52
   * Licensed under FreeBSD License.
   * See http://animista.net/license for more info. 
   * w: http://animista.net, t: @cssanimista
   * ---------------------------------------------- */

/**
   * ----------------------------------------
   * animation slide-fwd-top
   * ----------------------------------------
   */
@
-webkit-keyframes slide-fwd-top { 0% {
	-webkit-transform: translateZ(0) translateY(0);
	transform: translateZ(0) translateY(0);
}

100


%
{
-webkit-transform


:


translateZ
(


160px


)


translateY
(


-100px


)
;


transform


:


translateZ
(


160px


)


translateY
(


-100px


)
;


}
}
@
keyframes slide-fwd-top { 0% {
	-webkit-transform: translateZ(0) translateY(0);
	transform: translateZ(0) translateY(0);
}

100


%
{
-webkit-transform


:


translateZ
(


160px


)


translateY
(


-100px


)
;


transform


:


translateZ
(


160px


)


translateY
(


-100px


)
;


}
}

/*
INIZIO PARTE PAGINE SCHEDA STANDARD E AMMINISTRATORE ANIMALI E PIANTE
*/
.box {
	display: block;
	position: -ms-page;
}

#nomeanimale {
	text-align: center;
	font-family: "Gill Sans", "Gill Sans MT", Calibri, "Trebuchet MS",
		sans-serif;
}

.gestionea {
	margin-top: 1cm;
	font-size: auto;
	width: auto;
}

.imgstandard {
	border: dotted 5px #1b4428;
	width: 350px;
	margin-top: 2cm;
	margin-left: 0;
	margin-right: 0;
	height: 220px;
}

.imggestione {
	border: dotted 5px #1b4428;
	width: 350px;
	margin-top: 1.5cm;
	margin-right: 3cm;
	margin-bottom: 1cm;
	height: 220px;
}

.pstandard {
	background-color: rgba(169, 169, 169, 0.438);
	border: solid 1px rgb(255, 255, 255);
	color: #012e0f;
	width: 380px;
	height: 220px;
	overflow-y: scroll;
	word-break: break-all;
	font-family: "Gill Sans", "Gill Sans MT", Calibri, "Trebuchet MS",
		sans-serif;
}

.pgestione {
	background-color: rgba(169, 169, 169, 0.438);
	border: solid 1px rgb(255, 255, 255);
	color: #012e0f;
	width: 380px;
	height: 220px;
	position: relative;
	left: 40px;
	bottom: 20px;
	overflow-y: scroll;
	word-break: break-all;
	font-family: "Gill Sans", "Gill Sans MT", Calibri, "Trebuchet MS",
		sans-serif;
}

.bottonex {
	text-align: center;
	width: 4.6cm;
	border-radius: 7px;
	border-color: #1b4428;
	height: 28px;
}

.bottoney {
	text-align: center;
	width: 4.6cm;
	border-radius: 7px;
	border-color: #1b4428;
	position: relative;
	top: 35px;
	left: 0;
	height: 28px;
}

.updatename {
	border: solid #012e0f;
	border-radius: 20px;
	z-index: 1;
	background-color: rgb(202, 202, 202);
	top: 50%;
	left: 50%;
	width: 26em;
	height: 12em;
	margin-top: -9em;
	margin-left: -15em;
	position: absolute;
}

.updateimage {
	border: solid #012e0f;
	border-radius: 20px;
	z-index: 1;
	background-color: rgb(202, 202, 202);
	top: 50%;
	left: 50%;
	width: 26em;
	height: 12em;
	margin-top: -9em;
	margin-left: -15em;
	position: absolute;
}

.updatedescr {
	border: solid #012e0f;
	border-radius: 20px;
	z-index: 1;
	background-color: rgb(202, 202, 202);
	top: 50%;
	left: 50%;
	width: 26em;
	height: 12em;
	margin-top: -9em;
	margin-left: -15em;
	position: absolute;
}

.update {
	margin-top: 1cm;
	margin-right: 1cm;
	margin-left: 1cm;
}

.update td {
	position: relative;
	bottom: 0.6cm;
	color: #012e0f;
	font-size: 20px;
	text-align: center;
	font-family: "Gill Sans", "Gill Sans MT", Calibri, "Trebuchet MS",
		sans-serif;
}

.update #B {
	width: 8cm;
}

.update #C {
	margin-top: 2px;
	border-radius: 10px;
	border: #012e0f solid;
	color: #012e0f;
	font-size: 20px;
	text-align: center;
	font-family: "Gill Sans", "Gill Sans MT", Calibri, "Trebuchet MS",
		sans-serif;
}

.upback {
	width: 1cm;
	height: 25px;
	border-radius: 50%;
	text-align: center;
}

@media screen and (max-width: 1700px) {
	body {
		background-color: rgb(255, 230, 0);
	}
	.col-10 {
		border: solid rgb(255, 0, 0) 3px;
	}
}
</style>
</head>
<body>
	<div class="row">
		<div class="col-3"></div>
		<div class="col-6">
			<h1 id="nomeanimale">GESTIONE ANIMALE</h1>
		</div>
		<div class="col-3"></div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-1"></div>
			<div class="col-10" style="border: solid black 3px"></div>
			<div class="col-1"></div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-2"></div>
			<div class="col-6">
				<h3 class="gestionea"><%=a.getNome()%></h3>
			</div>
			<div class="col-1">
				<button class="bottoney" onclick="nohide1()">Modifica Nome</button>
			</div>
			<div class="col-1"></div>
		</div>
		<hr />
		<div class="row">
			<div class="col-2"></div>
			<div class="col-3">
				<img class="imggestione" src="<%=a.getImg()%>" width="400px"
					height="400px" />
			</div>
			<div class="col-1"></div>
			<div class="col-4">
				<p class="pgestione" style="margin-top: 75px">
					<%=a.getDescr()%>
				</p>
			</div>
		</div>
		<div class="row">
			<div class="col-3"></div>
			<div class="col-3">
				<button class="bottonex" onclick="nohide2()">Modifica
					Immagine</button>
			</div>
			<div class="col-1"></div>
			<div class="col-1">
				<button class="bottonex" onclick="nohide3()">Modifica
					Descrizione</button>
			</div>
		</div>
		<a href="elencoanimali"><button class="bottonex">indietro</button></a>
		<div class="updatename" id="XX" hidden>
			<table class="update">
				<tr>
					<button class="upback" onclick="hide1()">X</button>
				</tr>
				<tr>
					<td>MODIFICA NOME</td>
				</tr>
				<tr>
					<td>
						<form action="/modificaanimale" method="get">
							<input type="text" name="id" value="<%=a.getId()%>" readonly hidden ="true"><br>
							NOME <input type="text" name="nome" value="<%=a.getNome()%>"><br>
							<input type="text" name="sesso" value="<%=a.getSesso()%>" readonly hidden ="true"><br>
							<input type="text" name="classe" value="<%=a.getClasse()%>" readonly hidden ="true"><br> 
							<input type="text" name="descr" value="<%=a.getDescr()%>" readonly hidden ="true"><br>
							<input type="submit" value="AGGIORNA">
						</form>
					</td>
				</tr>
			</table>
		</div>
		<div class="updateimage" id="XY" hidden = "true">
			<table class="update">
				<tr>
					<button class="upback" onclick="hide2()">X</button>
				</tr>
				<tr>
					<td>MODIFICA IMMAGINE</td>
				</tr>
				<tr>
					<td>
						<form method="post" action="uploadImageA"
							enctype="multipart/form-data">
							<input type="text" name="id" value="<%=a.getId()%>" readonly
								hidden="true"><br> <input type="file" name="image"
								value="<%=a.getImg()%>" /> <input type="submit"
								value="Upload" />
						</form>
					</td>
				</tr>
			</table>
		</div>
		<div class="updatedescr" id="YY" hidden>
			<table class="update">
				<tr>
					<button class="upback" onclick="hide3()">X</button>
				</tr>
				<tr>
					<td>MODIFICA DESCRIZIONE</td>
				</tr>
				<tr>
					<td>
							<form action="/modificaanimale" method="get">
							DESCRIZIONE <input type="text" name="descr" value="<%=a.getDescr()%>"><br>
							<input type="text" name="id" value="<%=a.getId()%>" readonly hidden ="true"><br>
							<input type="text" name="nome" value="<%=a.getNome()%>" readonly hidden ="true"><br>
							 <input type="text" name="sesso" value="<%=a.getSesso()%>" readonly hidden ="true"><br>
						    	<input type="text" name="classe" value="<%=a.getClasse()%>" readonly hidden ="true"><br> 
							<input type="submit" value="AGGIORNA">
						</form>
					</td>
				</tr>
			</table>
		</div>
	</div>

</body>
</html>
